name: RickAndMorty

configs:
  Debug: debug
  Release: release

settings:
  DEVELOPMENT_TEAM: H7BM7N56V5

options:
  bundleIdPrefix: com.vcoutasso

targets:
  RickAndMorty:
    type: application
    platform: iOS
    deploymentTarget: 15.0
    settings:
      TARGETED_DEVICE_FAMILY: 1
      INFOPLIST_FILE: RickAndMorty/Supporting-Files/Info.plist
    sources: RickAndMorty

  RickAndMortyTests:
    type: bundle.unit-test
    platform: iOS
    sources: RickAndMortyTests
    dependencies:
      - target: RickAndMorty

  RickAndMortyUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: RickAndMortyUITests
    dependencies:
      - target: RickAndMorty

schemes:
  RickAndMorty:
    build:
      targets:
        RickAndMorty: all
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: RickAndMortyTests
          parallelizable: true
          randomExecutionOrder: true

  RickAndMortyUITests:
    build:
      targets:
        RickAndMortyUITests: all
    test:
      config: Debug
      targets: 
        - name: RickAndMortyUITests
