name: RickAndMorty

settings:
  DEVELOPMENT_TEAM: H7BM7N56V5

options:
  bundleIdPrefix: com.vcoutasso

targets:
  RickAndMorty:
    type: application
    platform: iOS
    deploymentTarget: 15.0
    settings:
      TARGETED_DEVICE_FAMILY: 1
    sources: RickAndMorty
    scheme:
      testTargets:
        - RickAndMortyTests

  RickAndMortyTests:
    info:
      path: RickAndMorty/Supporting-Files/Info.plist
    type: bundle.unit-test
    platform: iOS
    sources: RickAndMortyTests
    settings:
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/RickAndMorty.app/RickAndMorty

  RickAndMortyUITests:
    info:
      path: RickAndMorty/Supporting-Files/Info.plist
    type: bundle.ui-testing
    platform: iOS
    sources: RickAndMortyUITests
    settings:
      TEST_TARGET_NAME: RickAndMorty
