name: RickAndMorty

settings:
  DEVELOPMENT_TEAM: H7BM7N56V5

options:
  bundleIdPrefix: com.vcoutasso

targets:
  RickAndMorty:
    type: application
    platform: iOS
    deploymentTarget: 15.0
    settings:
      TARGETED_DEVICE_FAMILY: 1
    sources: RickAndMorty
    scheme:
      testTargets:
        - RickAndMortyTests

  RickAndMortyTests:
    type: bundle.unit-test
    platform: iOS
    sources: RickAndMortyTests

  RickAndMortyUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: RickAndMortyUITests
    settings:
      TEST_TARGET_NAME: RickAndMorty
