name: RickAndMorty

configs:
  Debug: debug
  Release: release

settings:
  DEVELOPMENT_TEAM: H7BM7N56V5

options:
  bundleIdPrefix: com.vcoutasso

targets:
  RickAndMorty:
    type: application
    platform: iOS
    deploymentTarget: 15.0
    settings:
      TARGETED_DEVICE_FAMILY: 1
      INFOPLIST_FILE: RickAndMorty/Supporting-Files/Info.plist
    sources: RickAndMorty
    scheme:
      testTargets:
        - RickAndMortyTests

  RickAndMortyTests:
    info:
      path: RickAndMorty/Supporting-Files/Info.plist
    type: bundle.unit-test
    platform: iOS
    sources: RickAndMortyTests
    dependencies:
      - target: RickAndMorty

  RickAndMortyUITests:
    info:
      path: RickAndMorty/Supporting-Files/Info.plist
    type: bundle.ui-testing
    platform: iOS
    sources: RickAndMortyUITests
    dependencies:
      - target: RickAndMorty
