name: Tests

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  tests:
    runs-on: macos-11.0
    name: Tests
    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: List available Xcode versions
        run: ls /Applications | grep Xcode

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_13.0.app && /usr/bin/xcodebuild -version

      - name: Install xcodegen
        run: brew install xcodegen

      - name: Generate project
        run: make generate

      - name: Run unit tests
        run : xcodebuild test -scheme RickAndMorty -destination platform\=iOS\ Simulator,OS\=15.0,name\=iPhone\ 13 | xcpretty

     - name: Upload coverage to Codecov
       uses: codecov/codecov-action@v1.2.1

     - name: Run UI tests
       run : xcodebuild test -scheme RickAndMortyUITests -destination platform\=iOS\ Simulator,OS\=15.0,name\=iPhone\ 13 | xcpretty
